### ISSUE TITLE
support mac vim?

### ISSUE THREAD

**Issue by zhigangfang** [hrj/vim-DrawIt#1]
HI, is this support mac vim?

**Comment by hrj** [comment]
Hi @zhigangfang 

I don't know; I don't have a mac to test with.

The upstream just says vim 7.0 is required.

**Comment by zhigangfang** [comment]
@hrj tks
I can't drag the brush on mac vim, it's may  be compatibility problem. Have you ever been in such situation?

**Comment by hrj** [comment]
@zhigangfang Nope. Actually, I haven't used this in a long time.

Have you tried it on a linux system, to be sure that you are not using it wrongly?
